### PR TITLE
Moved larimer Q puller. Review/help needed on download_q function

### PR DESCRIPTION
**Pull request by SamStruthers**
moved the .R file to an RMD so that it is easier to understand structure and organize ideas. 

Ran into bug on download_q function. Any help would be appreciated if anyone is inspired by API things

When I run the inside of the function with a indv site url and number it runs fine(lines 158-159). After removing those, I try to use the function with same stuff (lines 160) and it won't create discharge_data obj so it errors. When I run in inside individually, then try to map over the two sites in the clp_data_url_test (line 177), it won't go past the length of the original discharge_data which was from a previous site and errors. I think once this is figured out when I can create a function for any site and any parameter on this website which would fill me with joy

### CODE REVIEW

**Comment by kathryn-willi** [comment]
I can try to help with this! I'll put this q_downloader on my to-do list for this week.

**Comment by steeleb** [comment]
Thank you Katie!! I'm at capacity with other things - if you need me to review/help/get stuck, let me know, but a thoughtful and thorough review is probably not in the cards for me this week. Sorry and thank you!!

**Comment by mbrousil** [comment]
@kathryn-willi I can also help if you need it, just lmk!

**Comment by SamStruthers** [comment]
No progress on download_q but modified some code in cap rod cleaning to work with Kampf data. More on this later

**Pull request merged**
